SRCDIR = ..

# Test programs to compile, and a list of sources for each.
# To add a new test, put its name on the PROGS list
# and then add a name_SRC line that lists its source files.
PROGS = cat cmp cp echo halt hex-dump ls mcat mcp mkdir pwd rm shell \
	bubsort insult lineup matmult recursor hello_world inputTesting \
	read_file_test write_test seek_test filesize_test halt_test \
	tell_test open-bad-ptr exec-missing

# Should work from project 2 onward.
cat_SRC = cat.c
cmp_SRC = cmp.c
cp_SRC = cp.c
echo_SRC = echo.c
halt_SRC = halt.c
hex-dump_SRC = hex-dump.c
insult_SRC = insult.c
lineup_SRC = lineup.c
ls_SRC = ls.c
recursor_SRC = recursor.c
rm_SRC = rm.c
hello_world_SRC = hello_world.c
inputTesting_SRC = inputTesting.c
read_file_test_SRC = read_file_test.c
write_test_SRC = write_test.c
seek_test_SRC = seek_test.c
filesize_test_SRC = filesize_test.c
halt_test_SRC = halt_test.c
tell_test_SRC = tell_test.c
open-bad-ptr_SRC = open-bad-ptr.c
exec-missing_SRC = exec-missing.c

# Should work in project 3; also in project 4 if VM is included.
bubsort_SRC = bubsort.c
matmult_SRC = matmult.c
mcat_SRC = mcat.c
mcp_SRC = mcp.c

# Should work in project 4.
mkdir_SRC = mkdir.c
pwd_SRC = pwd.c
shell_SRC = shell.c

include $(SRCDIR)/Make.config
include $(SRCDIR)/Makefile.userprog
